server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: msgassama
  auth-server-url: http://127.0.0.1:8080
  resource: springboot-keycloak
  public-client: true
  bearer-only: true